# Generated by Django 4.0.2 on 2022-05-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients_feedback_tracker_api", "0003_alter_translationsentences_sentence"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationsentences",
            name="qcSentence",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="translationworks",
            name="targetTextAfterQc",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="translationworks",
            name="targetText",
            field=models.TextField(null=True),
        ),
    ]
