# Generated by Django 4.0.2 on 2022-05-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clients_feedback_tracker_api",
            "0004_translationsentences_qcsentence_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbacks",
            name="qcerId",
        ),
        migrations.RemoveField(
            model_name="feedbacks",
            name="translatorId",
        ),
        migrations.AddField(
            model_name="translationworks",
            name="qcerId",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="translationworks",
            name="translatorId",
            field=models.IntegerField(null=True),
        ),
    ]
