# Generated by Django 4.0.2 on 2022-05-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_feedback_tracker_api', '0005_remove_feedbacks_qcerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationsentences',
            name='sourceSentence',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='translationworks',
            name='wordCount',
            field=models.IntegerField(null=True),
        ),
    ]
