# Generated by Django 4.0.2 on 2022-07-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_feedback_tracker_api', '0009_alter_contenttitles_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttitles',
            name='client',
            field=models.CharField(choices=[('Kakao Ent', 'Kakao'), ('NHN', 'Nhn'), ('Nuon', 'Nuon'), ('Piuri', 'Piuri'), ('Tappytoon Webtoon', 'Tappytoon Webtoon'), ('Tappytoon Webnovel', 'Tappytoon Webnovel'), ('Tapas', 'Tapas'), ('Naver', 'Naver'), ('Eineblume', 'Eineblume'), ('StoryX', 'Storyx'), ('Kanafeel', 'Kanafeel'), ('Lezhin', 'Lezhin'), ('Ridi corporation', 'Ridi')], default='Kakao Ent', max_length=20),
        ),
    ]
