# Generated by Django 4.0.2 on 2022-07-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_feedback_tracker_api', '0010_alter_contenttitles_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttitles',
            name='completedAt',
            field=models.DateField(null=True),
        ),
    ]
